name: Test building docs "to publish"

on:
  push:
    # Run when a change to these files is pushed to any branch. Without the "branches:" line, for some reason this will be run whenever a tag is pushed, even if the listed files aren't changed.
    branches: ['*']
    # But only when these files are updated:
    paths:
      - 'doc/doc-builder'
      - 'doc/build_docs_to_publish'
      - '.github/workflows/docs-to-publish.yml'
      - '.github/workflows/docs-build_to_publish-optionally-deploy.yml'

  pull_request:
    # Run on pull requests that change the listed files
    paths:
      - 'doc/doc-builder'
      - 'doc/build_docs_to_publish'
      - '.github/workflows/docs-to-publish.yml'
      - '.github/workflows/docs-build_to_publish-optionally-deploy.yml'

permissions:
  contents: read

jobs:

  build-to-publish-dont-deploy:
    name: Call reusable workflow with deploy false

    uses: ./.github/workflows/docs-build_to_publish-optionally-deploy.yml
    with:
      deploy: false
